// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2MIbWo3ootwmIihdxpg59-4VO2GK5bI8',
    appId: '1:724145259216:web:48d8e2278f7f5e59d694d5',
    messagingSenderId: '724145259216',
    projectId: 'studybuddy-2045e',
    authDomain: 'studybuddy-2045e.firebaseapp.com',
    storageBucket: 'studybuddy-2045e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7xkxSh6jRiYvEkMA4h449oAjZQRTdnv8',
    appId: '1:724145259216:android:52b03fe1477ef778d694d5',
    messagingSenderId: '724145259216',
    projectId: 'studybuddy-2045e',
    storageBucket: 'studybuddy-2045e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCrDe--adRKYRNe3b8aq2Gnxq6mga3Ys',
    appId: '1:724145259216:ios:5d93d0ec1dd7367fd694d5',
    messagingSenderId: '724145259216',
    projectId: 'studybuddy-2045e',
    storageBucket: 'studybuddy-2045e.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCrDe--adRKYRNe3b8aq2Gnxq6mga3Ys',
    appId: '1:724145259216:ios:5d93d0ec1dd7367fd694d5',
    messagingSenderId: '724145259216',
    projectId: 'studybuddy-2045e',
    storageBucket: 'studybuddy-2045e.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2MIbWo3ootwmIihdxpg59-4VO2GK5bI8',
    appId: '1:724145259216:web:e30f9b1f90c4352dd694d5',
    messagingSenderId: '724145259216',
    projectId: 'studybuddy-2045e',
    authDomain: 'studybuddy-2045e.firebaseapp.com',
    storageBucket: 'studybuddy-2045e.firebasestorage.app',
  );
}
